### ISSUE TITLE
运行Demo 点击Debug View Hierarchy 查看视图层级导致视图停止绘制？

### ISSUE THREAD

**Issue by Nomeqc** [Meituan-Dianping/Graver#1]
### Environment Details

* Graver version: 1.0.0
* iOS version:11.4.1
* Xcode version: 9.4.1
* Other informations:

### Expected behavior
点击`Debug View Hierarchy`后继续视图能正常显示

### Actual behavior
点击`Debug View Hierarchy`后视图无法正常显示

**Comment by zxfmpy** [comment]
我也发现这个问题了，准备来提issues，发现你已经提了

**Comment by StanOz** [comment]
![image](https://user-images.githubusercontent.com/12152553/50329672-327c7900-0533-11e9-861d-ea50efb2316f.png)

推测是 `-[WMGAsyncDrawView _displayLayer:rect:drawingStarted:drawingFinished:drawingInterrupted:]` 这方法里面的 drawBlock，在非主线程读取 layer 的 contentsScale 导致当前线程忙等待无法完成任务。我改成下面这样就没问题了：

![image](https://user-images.githubusercontent.com/12152553/50329688-4a53fd00-0533-11e9-8e1e-fd80c08e5ceb.png)

**Comment by RTiOS** [comment]
感谢关注,这个问题是由于系统各版本layer的getContentsScale实现方式不同,导致部分版本中子线程获取contentsScale的时候出现线程等待,调试的时候可以先把contentsScale移到主线程获取,来暂时避免此问题,我们会在下个版本修复,欢迎继续关注.
