### ISSUE TITLE
对外接口格式建议

### ISSUE THREAD

**Issue by Gocy015** [Meituan-Dianping/Graver#10]
### Context and Description

写法上鼓励链式调用（方法都会 return 自己），建议改成 block 形式声明，
`item.append(...).append(...)` 而不是 `
    [[[[item appendAttributedItem:text1] appendImageWithName:@"story_icon" size:CGSizeMake(18, 18)] appendWhiteSpaceWithWidth:5] appendAttributedItem:text2];`

### Environment Details

* Graver version:
* iOS version:
* Xcode version:
* Other informations:

**Comment by weiweijiang** [comment]
感谢您的建议，这是非常好的思路，我们后续会综合考虑各方建议，制定方案，推出对开发者更友好的调用方式，在后续版本中更新，欢迎持续关注。
