### ISSUE TITLE
图片加载建议改成 Protocol 的形式,交给项目自己处理

### ISSUE THREAD

**Issue by yang152412** [Meituan-Dianping/Graver#12]
图片加载深度集成了 `SDWebImage`，但是这样不太好，开源的话，无法保证其他项目也必须得用 SDWebImage，可以改为 用 Protocol 的形式来处理，将图片的下载 模块交给 项目自行处理。例如：

```
@property (nonatomic, strong) id <ImageDownloadProtocol> downloader;

```

**Comment by bilibilibilidong** [comment]
或者对图片加载集成自己的方案，抛开sd，

**Comment by ghsyy** [comment]
SDWebImage是业内非常优秀的图片加载相关框架。考虑到大多数场景的业务应用，对于Graver来说集成SDWebImage处理图片下载是更为方便作为第三方使用的。
如果涉及到和现有业务应用的图片下载存在冲突，建议考虑修改WMGImage类中的图片下载接口，集成业务中的图片下载框架。
当然你也可以以贡献代码提交PR的方式和我们一起共建。
