### ISSUE TITLE
能否提高sdwebimage的版本

### ISSUE THREAD

**Issue by bilibilibilidong** [Meituan-Dianping/Graver#13]
现在依赖的为sdwebimage的 4.2.1的版本，这个版本的sdwebimage提供的图片缓存判断的方法并不实用，甚至可以说很烂。

**Comment by weiweijiang** [comment]
感谢关注，由于考虑到不同接入方依赖的SDWebImage版本不同，我们暂时不升级，如果有需要，你也可以自己指定需要的版本，我们也会持续关注SDWebimage，如有重大更新，会持续跟进。
