### ISSUE TITLE
SDWebImage的依赖

### ISSUE THREAD

**Issue by aslanTT** [Meituan-Dianping/Graver#16]
s.dependency 'SDWebImage', '4.2.1'

希望版本号改下依赖的写法，我们项目用得更高版本的SDWebImage，导致依赖冲突。

**Comment by weiweijiang** [comment]
多谢反馈，使用4.2.1是因为是我们验证过的稳定版本，考虑到不同接入方依赖冲突，我们决定改为~>4.2兼容大部分使用的4+版本。
