### ISSUE TITLE
最后绘制成位图后，点击事件的无埋点方案就不能支持的把

### ISSUE THREAD

**Issue by karosLi** [Meituan-Dianping/Graver#21]
这里的点击事件跟texture的模拟点击是类似的，针对现有的 growingio的无埋点方案支持的不太友好把。

**Comment by ghsyy** [comment]
美团内部已针对绘制元素提供了埋点解决方案，方案大致上是提供给上层业务获取到任一绘制元素的frame等信息，基于此也提供了些遍历方法，判断某一个元素是否在当前屏幕内，以此来提供对曝光埋点的支持，点击埋点和原生使用差别不大，在点击回调的方法里添加统计上报即可。

以上描述是基于美团外卖内部自主设计研发的曝光埋点方案提供的兼容处理，这些兼容处理也具备一定的通用兼容性。具体结合growingio等埋点方案，需要结合实际来判断兼容的友好性。

上述对曝光、埋点的支持预计会在春节前后发布更新版本的时候带上，欢迎持续关注。后续我们也可以一起交流、共建对诸如无痕埋点等埋点方案的兼容处理。
