### ISSUE TITLE
Demo中Cell上的按钮为什么都没有添加点击事件？

### ISSUE THREAD

**Issue by SmallMX** [Meituan-Dianping/Graver#24]
应该怎样给Cell上的按钮添加点击事件？难道美团App上都是点击整个Cell？

**Comment by ghsyy** [comment]
可以看一下 WMGTextAttachment+Event

**Comment by SmallMX** [comment]
> 可以看一下WMGTextAttachment + Event
if (textDrawer.textLayout.attributedString == self.btnObj.value) {
        att.responseEvent = YES;
        [att addTarget:self action:@selector(clickTest:) forControlEvents:UIControlEventTouchUpInside];
    }
点击无效。。。。

**Comment by SmallMX** [comment]
既然开源了，能不能有个像样点的demo

**Comment by ghsyy** [comment]
真的很抱歉，给你带来了不好的体验，我们最晚会在3月底之前完成一波迭代更新，会带上点击事件处理的相对完整的demo。
