### ISSUE TITLE
美团到现在还没使用Auto Layout？

### ISSUE THREAD

**Issue by wangjiejacques** [Meituan-Dianping/Graver#25]
### Environment Details

* Graver version:
* iOS version:
* Xcode version:
* Other informations:

**Comment by indulgeIn** [comment]
兄台这个结论是怎么得出来的😓，这是性能优化框架，不是布局框架。

**Comment by wangjiejacques** [comment]
@indulgeIn 只是猜测，我看demo上的布局都是直接设置frame
