### ISSUE TITLE
将 WMPoiListTextView 放入 UIcollectionViewCell， reloadData 经常会闪烁

### ISSUE THREAD

**Issue by NeverAgain11** [Meituan-Dianping/Graver#26]
WMPoiListTextView 放入 cell，cell willDisplay 时设置数据，reloadData cell 有闪烁发生。
有什么办法避免 reloadData 闪烁的问题？

**Comment by GuitarPlayer-Ma** [comment]
你好，感谢你反馈的问题。为了方便我们尽快排查问题，请按照issue模板尽可能详细描述你的问题。issue模板链接：https://github.com/Meituan-Dianping/Graver/blob/master/docs/issue-template.md
