### ISSUE TITLE
性能和Texture对比如何，有没有相关的性能测试对比

### ISSUE THREAD

**Issue by jianjianhao** [Meituan-Dianping/Graver#29]

**Comment by RTiOS** [comment]
Texture是一款优秀的动态布局框架,它包含了节点的创建,解析,布局计算,异步渲染等一系列功能,而 Graver 目前只开源了渲染引擎部分,所以并没有做横向对比,感兴趣的话可以自己测试下~

**Comment by ghsyy** [comment]
![image](https://user-images.githubusercontent.com/8510557/58774551-a350b280-85f4-11e9-9315-10786fbb0da6.png)
截图显示了Graver在应用于外卖商家列表的部分技术指标数据，仅供参考。

Graver在设计之初，综合考虑了滚动性能、CPU占用、内存占用、以及与业务结合的融合度、易用性、使用成本等多方面因素。
从截图数据来看，各项技术指标是OK的。graver独创式的采用了面向视觉元素编程，在构建视图展示上是所见即所得的方式，一般我们在还原UI视觉稿的时候会考虑是否响应点击、展示元素是图片、文本，以及根据实际展示要求决定采用什么样的UI控件。在通过Graver构建视图的过程中，思考过程转变为图片、文本的拼接，并在需要的地方添加点击事件。从外卖的实践经验来看，开发效率相比原有方式提高了0.5倍。
