### ISSUE TITLE
WMGAsyncDrawView中drawRect:(CGRect)rect 和displayLayer:(CALayer *)layer中 去掉drawRect如何

### ISSUE THREAD

**Issue by ioswangpengwei** [Meituan-Dianping/Graver#30]
### Environment Details

* Graver version:
* iOS version:
* Xcode version:
* Other informations:

**Comment by ioswangpengwei** [comment]
实现了CALayerDelegate 代理的- (void)displayLayer:(CALayer *)layer 方法，就不会掉用- (void)drawRect:(CGRect)rect 方法了。不知道作者是否有其他的考虑，还是我知识尚浅！

**Comment by RTiOS** [comment]
1.默认策略是异步渲染,会调用displayLayer:(CALayer *)layer方法;
2.WMGAsyncDrawView 里重写了respondsToSelector:(SEL)aSelector 方法,用于判断是否实现了displayLayer:(CALayer *)layer,如果策略是同步,则会返回 NO, 从而调用drawRect:(CGRect)rect方法;
