### ISSUE TITLE
图层合并绘制线程问题

### ISSUE THREAD

**Issue by suweiz19890921** [Meituan-Dianping/Graver#34]
我想知道图层合并绘制线程是基于主线程上做的吗？

**Comment by ghsyy** [comment]
图层合并的绘制过程是在子线程，以并发形式进行。可参考https://github.com/Meituan-Dianping/Graver/blob/master/docs/FrameworkOverview.md#%E5%BC%82%E6%AD%A5%E7%BB%98%E5%88%B6
