### ISSUE TITLE
阴影设置没有生效

### ISSUE THREAD

**Issue by s9651guan** [Meituan-Dianping/Graver#35]
### Environment Details

* Graver version: 最新
* iOS version: IOS12
* Xcode version: 10.1
* Other informations: 

我的代码：
```
 WMGCanvasView *view = [[WMGCanvasView alloc] initWithFrame:CGRectMake(100, 100, 100, 100)];
    
    view.backgroundColor = [UIColor blueColor];
    view.cornerRadius = 4.0f;
    view.shadowColor = [UIColor redColor];
    view.shadowOffset = UIOffsetMake(0, 5);
    view.shadowBlur = 10.f;
    [self.view addSubview:view];
```
   
### Expected behavior
```
 CGRect frame = CGRectMake(100, 100, 100, 100);
    UIView *view = [[UIView alloc] initWithFrame:frame];
    // 背景色
    view.backgroundColor = [UIColor blueColor];
    [self.view addSubview:view];
    // 圆角
    view.layer.cornerRadius = 4.0f;
    // 阴影
    view.layer.shadowColor = [UIColor redColor].CGColor;
    view.layer.shadowOffset = CGSizeMake(0, 5);
    view.layer.shadowOpacity = 1;
    view.layer.shadowRadius = 10;
```

![WX20190505-180109](https://user-images.githubusercontent.com/30081060/57192149-c9d0ee80-6f5f-11e9-9394-cc2c4a66015d.png)

### Actual behavior
 圆角生效，但是阴影没有生效

感觉应该是上下文裁剪的问题，但确实造成了与系统api效果不一致的问题

![WX20190505-180209](https://user-images.githubusercontent.com/30081060/57192168-fa188d00-6f5f-11e9-8994-2f771e6fec05.png)

### Steps to Reproduce

**Comment by RTiOS** [comment]
谢谢你的反馈,我们后续会修复这个问题,欢迎持续关注~

**Comment by ghsyy** [comment]
谢谢您的反馈，该问题我们已列入排期，在19年的Q2结束前我们会尽力将该Feature补充到开源框架中。
