### ISSUE TITLE
复用问题

### ISSUE THREAD

**Issue by JxbSir** [Meituan-Dianping/Graver#37]
看了代码list中每个cell都是临时画的，那么请问还能复用吗？

### Environment Details

* Graver version:
* iOS version:
* Xcode version:
* Other informations:

**Comment by weiweijiang** [comment]
是可以复用的，代码list中的cell是把cell的类名作为identifier，使用系统的复用机制，然后在获取到cell后，通过[cell setupCellData:]方法进行内容的重绘。

**Comment by Vanson** [comment]
WMGBaseCell *cell = [tableView dequeueReusableCellWithIdentifier:NSStringFromClass(cellData.cellClass)];

可以复用的
