### ISSUE TITLE
模拟器外卖商家列表点击展开闪动且列表位置偏移

### ISSUE THREAD

**Issue by sxdxzkq** [Meituan-Dianping/Graver#8]
### Environment Details

* Graver version:1.0.0
* iOS version:模拟器 ios11
* Xcode version: 9.4
* Other informations:
真机未发现相同问题
### Steps to Reproduce

![kapture 2018-12-24 at 14 57 14](https://user-images.githubusercontent.com/16347380/50392794-70c0a500-078c-11e9-8ca5-17938307c13c.gif)

**Comment by RTiOS** [comment]
感谢关注!位移的问题是因为 [tableView reloadData] 的时候系统调用了adjustContentOffsetIfNecessary方法,导致列表位移,和系统版本有关,后续会解决此问题.对于cell闪动的问题,是因为demo中的绘制方案是基于一个画布的,刷新时整张图重新绘制导致,目前可以通过使用多个画板来避免此问题,后续我们也会做差异化和分区域绘制,欢迎继续关注.
